exp:
  model_backend: aurora

  nhrs_back: 24
  restart: False
  rpath: './output/<previous_exp_name>/'
  obspath: '/scratch3/NCEPDEV/da/Jeffrey.Whitaker/psobs'
  nobs_max: 15000
  ic_suffix: '12h_5it'
  sdate: '2015-01-01T00'
  n_init: 1
  dt_init: 12
  save_levs: [500]
  cycle: False
  exp_name: 'smoke_test_aurora'

  path_model: './backends/aurora/hf_cache/models--microsoft--aurora/snapshots/a96afd7ee6d65e3bd2d476f3be798a25a56f2296/'
  device: 'cuda'
  path_output: './output/'
  ic_cache: './ic_cache/'
  print_every: 1
  oberrstart: 1.0
  oberrdeltaperday: 0.25

windows:
  '1':
    n_verif: 2
    dt_verif: 6
    learn_rate: 1.0e-2
    weight_decay: 1.0e-3
    max_epoch: 5
    warmup_steps: 1
    start_factor: 0.5
    end_factor: 0.5
    bg_check: 4.
    zthresh: 500.
    zconst: 0.003
    suffix: ''
