exp:
  model_backend: ace2

  nhrs_back: 48
  restart: False
  rpath: './output/<previous_exp_name>/'
  obspath: '/scratch3/NCEPDEV/da/Jeffrey.Whitaker/psobs'
  nobs_max: 15000
  ic_suffix: '120h_50it'
  sdate: '2015-01-01T00'
  n_init: 1
  dt_init: 6
  save_levs: [1000, 850, 500, 250, 50]
  cycle: False
  exp_name: 'smoke_test_ace2'

  path_model: './backends/ace2/ACE2-ERA5/'
  model_name: 'ace2_era5_ckpt.tar'
  device: 'cuda'
  path_output: './output/'
  ic_cache: './ic_cache_ace2/'
  print_every: 1
  oberrstart: -1
  oberrdeltaperday: 0
  # ps_operator defaults to 'ps_native' for ACE2
  checkpoint_stride: 2 # checkpoint_stride: 0 runs out of memory on H100
  control_variables: [air_temperature, specific_total_water, eastward_wind, northward_wind, PRESsfc, surface_temperature, TMP2m, Q2m, UGRD10m, VGRD10m] # this is the full list, nothing excluded (the default)

windows:
  '5':
    n_verif: 20
    dt_verif: 6
    dt_obs: 6
    learn_rate: 2.0e-3
    weight_decay: 1.0e-3
    max_epoch: 50
    warmup_steps: 10
    start_factor: 0.1
    end_factor: 1
    bg_check: 4.
    zthresh: 500.
    zconst: 0.003
    suffix: ''
